-- Generated from clinic_full_export.xlsx.
-- Raw import schema: every Excel cell is stored as TEXT to preserve source data.
DROP SCHEMA IF EXISTS "robo_raw" CASCADE;
CREATE SCHEMA "robo_raw";

CREATE TABLE "robo_raw"."admin_help_templates" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "topic" TEXT,
  "title" TEXT,
  "title_vi" TEXT,
  "content" TEXT,
  "content_vi" TEXT,
  "is_active" TEXT,
  "created_at" TEXT
);

CREATE TABLE "robo_raw"."ai_boundary_metadata" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "version" TEXT,
  "description" TEXT,
  "views_included" TEXT,
  "rpcs_included" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

CREATE TABLE "robo_raw"."appointment_requests" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "organization_id" TEXT,
  "clinic_id" TEXT,
  "source" TEXT,
  "source_reference" TEXT,
  "patient_info" TEXT,
  "preferred_date" TEXT,
  "preferred_time_start" TEXT,
  "preferred_time_end" TEXT,
  "is_flexible_time" TEXT,
  "department_hint" TEXT,
  "service_hint" TEXT,
  "doctor_preference_id" TEXT,
  "symptom_data" TEXT,
  "ai_consultation_result" TEXT,
  "ai_summary" TEXT,
  "status" TEXT,
  "priority" TEXT,
  "reviewed_by" TEXT,
  "reviewed_at" TEXT,
  "review_notes" TEXT,
  "rejection_reason" TEXT,
  "converted_appointment_id" TEXT,
  "converted_patient_id" TEXT,
  "converted_at" TEXT,
  "converted_by" TEXT,
  "expires_at" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "created_by" TEXT,
  "updated_by" TEXT,
  "is_deleted" TEXT,
  "deleted_at" TEXT,
  "deleted_by" TEXT
);

CREATE TABLE "robo_raw"."appointments" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "clinic_id" TEXT,
  "patient_id" TEXT,
  "doctor_id" TEXT,
  "appointment_date" TEXT,
  "start_time" TEXT,
  "end_time" TEXT,
  "duration_minutes" TEXT,
  "visit_type" TEXT,
  "status" TEXT,
  "service_id" TEXT,
  "chief_complaint" TEXT,
  "notes" TEXT,
  "confirmed_at" TEXT,
  "confirmed_by" TEXT,
  "arrived_at" TEXT,
  "checked_in_by" TEXT,
  "completed_at" TEXT,
  "cancelled_at" TEXT,
  "cancelled_by" TEXT,
  "cancellation_reason" TEXT,
  "ai_suggested_duration" TEXT,
  "ai_suggested_doctor_id" TEXT,
  "ai_suggestion_accepted" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "created_by" TEXT,
  "updated_by" TEXT,
  "is_deleted" TEXT,
  "deleted_at" TEXT,
  "deleted_by" TEXT
);

CREATE TABLE "robo_raw"."beds" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "clinic_id" TEXT,
  "room_id" TEXT,
  "bed_code" TEXT,
  "bed_name" TEXT,
  "bed_type" TEXT,
  "is_active" TEXT,
  "display_order" TEXT,
  "notes" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "created_by" TEXT,
  "updated_by" TEXT
);

CREATE TABLE "robo_raw"."clinic_currencies" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "clinic_id" TEXT,
  "currency_code" TEXT,
  "is_default" TEXT,
  "exchange_rate_to_vnd" TEXT,
  "display_order" TEXT,
  "created_at" TEXT,
  "created_by" TEXT,
  "units_per_default_unit" TEXT
);

CREATE TABLE "robo_raw"."clinic_currency_rate_versions" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "clinic_id" TEXT,
  "currency_code" TEXT,
  "effective_from" TEXT,
  "units_per_default_unit" TEXT,
  "created_at" TEXT,
  "created_by" TEXT
);

CREATE TABLE "robo_raw"."clinic_feature_flags" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "clinic_id" TEXT,
  "feature_code" TEXT,
  "is_enabled" TEXT,
  "config" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

CREATE TABLE "robo_raw"."clinic_general_settings" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "clinic_id" TEXT,
  "timezone" TEXT,
  "date_format" TEXT,
  "time_format" TEXT,
  "working_hours_start" TEXT,
  "working_hours_end" TEXT,
  "lunch_break_start" TEXT,
  "lunch_break_end" TEXT,
  "appointment_slot_duration" TEXT,
  "max_advance_booking_days" TEXT,
  "allow_online_booking" TEXT,
  "require_phone_verification" TEXT,
  "send_appointment_reminders" TEXT,
  "reminder_hours_before" TEXT,
  "auto_cancel_no_show_minutes" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "patient_code_prefix" TEXT,
  "patient_code_min_length" TEXT,
  "appointment_code_prefix" TEXT,
  "appointment_code_min_length" TEXT,
  "payment_code_prefix" TEXT,
  "payment_code_min_length" TEXT,
  "drug_code_prefix" TEXT,
  "drug_code_min_length" TEXT,
  "pharmacy_code_prefix" TEXT,
  "pharmacy_code_min_length" TEXT,
  "prescription_code_prefix" TEXT,
  "prescription_code_min_length" TEXT,
  "supplier_code_prefix" TEXT,
  "supplier_code_min_length" TEXT,
  "warehouse_code_prefix" TEXT,
  "warehouse_code_min_length" TEXT,
  "visit_code_prefix" TEXT,
  "visit_code_min_length" TEXT,
  "imaging_code_prefix" TEXT,
  "imaging_code_min_length" TEXT,
  "lab_code_prefix" TEXT,
  "lab_code_min_length" TEXT,
  "currency" TEXT,
  "invoice_template_registry" TEXT
);

CREATE TABLE "robo_raw"."clinic_memberships" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "user_id" TEXT,
  "clinic_id" TEXT,
  "is_active" TEXT,
  "joined_at" TEXT,
  "deactivated_at" TEXT,
  "deactivation_reason" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "created_by" TEXT,
  "updated_by" TEXT,
  "is_deleted" TEXT,
  "deleted_at" TEXT,
  "deleted_by" TEXT
);

CREATE TABLE "robo_raw"."clinic_subscriptions" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "clinic_id" TEXT,
  "plan_id" TEXT,
  "status" TEXT,
  "started_at" TEXT,
  "expires_at" TEXT,
  "cancelled_at" TEXT,
  "ai_calls_used_this_month" TEXT,
  "ai_calls_reset_at" TEXT,
  "payment_reference" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "created_by" TEXT,
  "updated_by" TEXT
);

CREATE TABLE "robo_raw"."clinic_type_ai_capabilities" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "clinic_type" TEXT,
  "ai_capability" TEXT,
  "is_allowed" TEXT,
  "created_at" TEXT
);

CREATE TABLE "robo_raw"."clinic_type_modules" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "clinic_type" TEXT,
  "module_code" TEXT,
  "is_allowed" TEXT,
  "created_at" TEXT
);

CREATE TABLE "robo_raw"."clinics" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "name" TEXT,
  "name_short" TEXT,
  "license_number" TEXT,
  "tax_id" TEXT,
  "phone" TEXT,
  "email" TEXT,
  "address" TEXT,
  "district" TEXT,
  "city" TEXT,
  "timezone" TEXT,
  "currency" TEXT,
  "locale" TEXT,
  "patient_code_prefix" TEXT,
  "patient_code_sequence" TEXT,
  "status" TEXT,
  "onboarded_at" TEXT,
  "onboarded_by" TEXT,
  "suspended_at" TEXT,
  "suspended_reason" TEXT,
  "offboarded_at" TEXT,
  "offboarded_by" TEXT,
  "offboarding_reason" TEXT,
  "onboarding_template" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "created_by" TEXT,
  "updated_by" TEXT,
  "is_deleted" TEXT,
  "deleted_at" TEXT,
  "deleted_by" TEXT,
  "deletion_reason" TEXT,
  "is_demo" TEXT,
  "demo_reset_at" TEXT,
  "demo_expires_at" TEXT,
  "clinic_type" TEXT,
  "enabled_modules" TEXT,
  "organization_id" TEXT,
  "clinic_type_new" TEXT,
  "latitude" TEXT,
  "longitude" TEXT,
  "logo_url" TEXT
);

CREATE TABLE "robo_raw"."crm_corporate_accounts" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "clinic_id" TEXT,
  "company_name" TEXT,
  "tax_code" TEXT,
  "address" TEXT,
  "city" TEXT,
  "phone" TEXT,
  "email" TEXT,
  "website" TEXT,
  "industry" TEXT,
  "employee_count" TEXT,
  "contract_count" TEXT,
  "total_revenue_vnd" TEXT,
  "notes" TEXT,
  "is_active" TEXT,
  "is_deleted" TEXT,
  "deleted_at" TEXT,
  "deleted_by" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "created_by" TEXT,
  "updated_by" TEXT
);

CREATE TABLE "robo_raw"."crm_loyalty_tiers" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "clinic_id" TEXT,
  "tier" TEXT,
  "min_points" TEXT,
  "discount_percent" TEXT,
  "benefits" TEXT,
  "is_active" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "created_by" TEXT,
  "updated_by" TEXT
);

CREATE TABLE "robo_raw"."diagnostic_machines" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "clinic_id" TEXT,
  "machine_code" TEXT,
  "machine_name" TEXT,
  "modality" TEXT,
  "ae_title" TEXT,
  "location" TEXT,
  "manufacturer" TEXT,
  "model" TEXT,
  "serial_number" TEXT,
  "is_active" TEXT,
  "notes" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "created_by" TEXT,
  "updated_by" TEXT
);

CREATE TABLE "robo_raw"."diagnostic_walk_in_patients" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "clinic_id" TEXT,
  "queue_number" TEXT,
  "status" TEXT,
  "patient_id" TEXT,
  "patient_name" TEXT,
  "patient_phone" TEXT,
  "patient_dob" TEXT,
  "patient_gender" TEXT,
  "patient_id_number" TEXT,
  "arrival_time" TEXT,
  "registered_at" TEXT,
  "registered_by" TEXT,
  "consulting_doctor_id" TEXT,
  "consulting_room_id" TEXT,
  "consultation_started_at" TEXT,
  "consultation_ended_at" TEXT,
  "clinical_notes" TEXT,
  "diagnostic_order_id" TEXT,
  "order_items" TEXT,
  "total_amount" TEXT,
  "payment_status" TEXT,
  "paid_amount" TEXT,
  "paid_at" TEXT,
  "cashier_id" TEXT,
  "invoice_number" TEXT,
  "payment_method" TEXT,
  "sample_collected_at" TEXT,
  "sample_collector_id" TEXT,
  "sample_notes" TEXT,
  "sent_to_lab_at" TEXT,
  "lab_received_at" TEXT,
  "lab_completed_at" TEXT,
  "result_ready_at" TEXT,
  "result_delivered_at" TEXT,
  "delivery_method" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "created_by" TEXT,
  "updated_by" TEXT,
  "result_file_url" TEXT,
  "reading_doctor_id" TEXT,
  "reading_started_at" TEXT,
  "reading_completed_at" TEXT,
  "reading_interpretation" TEXT,
  "reading_recommendations" TEXT,
  "follow_up_date" TEXT,
  "follow_up_notes" TEXT,
  "prescription_notes" TEXT,
  "currency_code" TEXT,
  "lab_technician_id" TEXT,
  "partner_lab_request_id" TEXT,
  "imaging_technician_id" TEXT,
  "pacs_integration" TEXT,
  "result_verified_by" TEXT,
  "result_verified_at" TEXT,
  "soft_copy_sent_at" TEXT,
  "soft_copy_sent_via" TEXT
);

CREATE TABLE "robo_raw"."doctor_schedules" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "clinic_id" TEXT,
  "doctor_id" TEXT,
  "room_id" TEXT,
  "day_of_week" TEXT,
  "start_time" TEXT,
  "end_time" TEXT,
  "is_active" TEXT,
  "notes" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "created_by" TEXT,
  "updated_by" TEXT
);

CREATE TABLE "robo_raw"."examination_zones" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "clinic_id" TEXT,
  "code" TEXT,
  "name" TEXT,
  "name_en" TEXT,
  "description" TEXT,
  "floor" TEXT,
  "display_order" TEXT,
  "is_active" TEXT,
  "created_at" TEXT,
  "created_by" TEXT,
  "updated_at" TEXT,
  "updated_by" TEXT
);

CREATE TABLE "robo_raw"."group_examinations" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "clinic_id" TEXT,
  "company_name" TEXT,
  "company_tax_code" TEXT,
  "company_address" TEXT,
  "company_phone" TEXT,
  "company_email" TEXT,
  "contract_number" TEXT,
  "contract_date" TEXT,
  "contract_value" TEXT,
  "session_name" TEXT,
  "session_code" TEXT,
  "exam_date" TEXT,
  "expected_count" TEXT,
  "actual_count" TEXT,
  "service_package_id" TEXT,
  "package_name" TEXT,
  "package_price" TEXT,
  "contact_name" TEXT,
  "contact_phone" TEXT,
  "contact_email" TEXT,
  "payment_status" TEXT,
  "total_amount" TEXT,
  "paid_amount" TEXT,
  "payment_notes" TEXT,
  "status" TEXT,
  "notes" TEXT,
  "created_at" TEXT,
  "created_by" TEXT,
  "updated_at" TEXT,
  "updated_by" TEXT,
  "is_deleted" TEXT,
  "deleted_at" TEXT,
  "deleted_by" TEXT
);

CREATE TABLE "robo_raw"."lis_accession_counters" (
  "_excel_row_number" INTEGER NOT NULL,
  "clinic_id" TEXT,
  "date_key" TEXT,
  "last_seq" TEXT
);

CREATE TABLE "robo_raw"."location_countries" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "code" TEXT,
  "name" TEXT,
  "name_en" TEXT,
  "phone_code" TEXT,
  "is_active" TEXT,
  "display_order" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "name_km" TEXT
);

CREATE TABLE "robo_raw"."location_provinces" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "country_id" TEXT,
  "code" TEXT,
  "name" TEXT,
  "name_en" TEXT,
  "is_active" TEXT,
  "display_order" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "name_km" TEXT
);

CREATE TABLE "robo_raw"."medical_records" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "clinic_id" TEXT,
  "visit_id" TEXT,
  "patient_id" TEXT,
  "doctor_id" TEXT,
  "status" TEXT,
  "chief_complaint" TEXT,
  "present_illness" TEXT,
  "ai_draft_present_illness" TEXT,
  "examination_findings" TEXT,
  "ai_draft_examination_findings" TEXT,
  "ai_suggested_diagnosis" TEXT,
  "confirmed_diagnosis" TEXT,
  "diagnosis_confirmed_by" TEXT,
  "diagnosis_confirmed_at" TEXT,
  "diagnosis_icd_code" TEXT,
  "treatment_plan" TEXT,
  "ai_draft_treatment_plan" TEXT,
  "doctor_notes" TEXT,
  "ai_draft_notes" TEXT,
  "follow_up_required" TEXT,
  "follow_up_date" TEXT,
  "follow_up_notes" TEXT,
  "finalized_at" TEXT,
  "finalized_by" TEXT,
  "amendment_count" TEXT,
  "last_amended_at" TEXT,
  "amendment_reason" TEXT,
  "schema_version" TEXT,
  "record_version" TEXT,
  "data_classification" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "created_by" TEXT,
  "updated_by" TEXT,
  "is_deleted" TEXT,
  "deleted_at" TEXT,
  "deleted_by" TEXT,
  "deletion_reason" TEXT
);

CREATE TABLE "robo_raw"."organization_memberships" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "organization_id" TEXT,
  "user_id" TEXT,
  "role" TEXT,
  "is_active" TEXT,
  "invited_at" TEXT,
  "joined_at" TEXT,
  "invited_by" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

CREATE TABLE "robo_raw"."organizations" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "name" TEXT,
  "name_short" TEXT,
  "legal_name" TEXT,
  "tax_id" TEXT,
  "business_license" TEXT,
  "email" TEXT,
  "phone" TEXT,
  "website" TEXT,
  "address" TEXT,
  "city" TEXT,
  "country" TEXT,
  "timezone" TEXT,
  "locale" TEXT,
  "currency" TEXT,
  "share_patient_index" TEXT,
  "centralized_billing" TEXT,
  "max_clinics" TEXT,
  "enabled_modules" TEXT,
  "settings" TEXT,
  "status" TEXT,
  "onboarded_at" TEXT,
  "suspended_at" TEXT,
  "suspended_reason" TEXT,
  "subscription_plan" TEXT,
  "subscription_expires_at" TEXT,
  "created_at" TEXT,
  "created_by" TEXT,
  "updated_at" TEXT,
  "updated_by" TEXT,
  "deleted_at" TEXT,
  "deleted_by" TEXT,
  "is_deleted" TEXT
);

CREATE TABLE "robo_raw"."paraclinical_orders" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "clinic_id" TEXT,
  "visit_id" TEXT,
  "patient_id" TEXT,
  "order_type" TEXT,
  "service_id" TEXT,
  "service_code" TEXT,
  "service_name" TEXT,
  "status" TEXT,
  "priority" TEXT,
  "ordered_by" TEXT,
  "ordered_at" TEXT,
  "collected_by" TEXT,
  "collected_at" TEXT,
  "processed_by" TEXT,
  "processed_at" TEXT,
  "completed_by" TEXT,
  "completed_at" TEXT,
  "cancelled_by" TEXT,
  "cancelled_at" TEXT,
  "cancellation_reason" TEXT,
  "result_summary" TEXT,
  "result_file_url" TEXT,
  "result_data" TEXT,
  "notes" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "created_by" TEXT,
  "updated_by" TEXT,
  "is_deleted" TEXT,
  "deleted_at" TEXT,
  "deleted_by" TEXT,
  "ris_accession" TEXT,
  "ris_placer_line_id" TEXT,
  "walk_in_id" TEXT,
  "lis_sent_at" TEXT,
  "lis_received_at" TEXT,
  "lis_machine_code" TEXT,
  "lis_technician_code" TEXT,
  "lis_approved_by" TEXT,
  "lis_status" TEXT
);

CREATE TABLE "robo_raw"."partner_audit_logs" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "partner_id" TEXT,
  "clinic_id" TEXT,
  "user_id" TEXT,
  "action" TEXT,
  "entity_type" TEXT,
  "entity_id" TEXT,
  "ip_address_hash" TEXT,
  "user_agent" TEXT,
  "metadata" TEXT,
  "created_at" TEXT
);

CREATE TABLE "robo_raw"."partner_clinics" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "clinic_id" TEXT,
  "name" TEXT,
  "name_short" TEXT,
  "partner_type" TEXT,
  "phone" TEXT,
  "email" TEXT,
  "contact_person" TEXT,
  "address" TEXT,
  "city" TEXT,
  "district" TEXT,
  "contract_code" TEXT,
  "partnership_type" TEXT,
  "commission_rate" TEXT,
  "notes" TEXT,
  "is_active" TEXT,
  "created_at" TEXT,
  "created_by" TEXT,
  "updated_at" TEXT,
  "updated_by" TEXT,
  "organization_id" TEXT
);

CREATE TABLE "robo_raw"."partner_lab_requests" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "partner_id" TEXT,
  "clinic_id" TEXT,
  "organization_id" TEXT,
  "accession_number" TEXT,
  "barcode" TEXT,
  "patient_name" TEXT,
  "patient_phone" TEXT,
  "patient_dob" TEXT,
  "patient_gender" TEXT,
  "patient_id_number" TEXT,
  "patient_address" TEXT,
  "status" TEXT,
  "priority" TEXT,
  "sample_type" TEXT,
  "collection_method" TEXT,
  "clinical_notes" TEXT,
  "requested_at" TEXT,
  "confirmed_at" TEXT,
  "sample_collected_at" TEXT,
  "processing_started_at" TEXT,
  "completed_at" TEXT,
  "verified_at" TEXT,
  "delivered_at" TEXT,
  "cancelled_at" TEXT,
  "cancellation_reason" TEXT,
  "estimated_completion_at" TEXT,
  "total_amount" TEXT,
  "currency_code" TEXT,
  "created_at" TEXT,
  "created_by" TEXT,
  "updated_at" TEXT,
  "updated_by" TEXT
);

CREATE TABLE "robo_raw"."partner_onsite_collections" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "request_id" TEXT,
  "partner_id" TEXT,
  "clinic_id" TEXT,
  "collection_address" TEXT,
  "collection_city" TEXT,
  "collection_district" TEXT,
  "location_notes" TEXT,
  "contact_person" TEXT,
  "contact_phone" TEXT,
  "preferred_date" TEXT,
  "preferred_time_start" TEXT,
  "preferred_time_end" TEXT,
  "scheduled_at" TEXT,
  "assigned_collector_id" TEXT,
  "assigned_at" TEXT,
  "status" TEXT,
  "departed_at" TEXT,
  "arrived_at" TEXT,
  "collected_at" TEXT,
  "returned_to_lab_at" TEXT,
  "collection_notes" TEXT,
  "cancellation_reason" TEXT,
  "created_at" TEXT,
  "created_by" TEXT,
  "updated_at" TEXT,
  "updated_by" TEXT
);

CREATE TABLE "robo_raw"."partner_users" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "partner_id" TEXT,
  "user_id" TEXT,
  "clinic_id" TEXT,
  "organization_id" TEXT,
  "role" TEXT,
  "full_name" TEXT,
  "email" TEXT,
  "phone" TEXT,
  "is_active" TEXT,
  "last_login_at" TEXT,
  "created_at" TEXT,
  "created_by" TEXT,
  "updated_at" TEXT,
  "updated_by" TEXT
);

CREATE TABLE "robo_raw"."patient_question_templates" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "category" TEXT,
  "question_text" TEXT,
  "question_text_vi" TEXT,
  "display_order" TEXT,
  "is_active" TEXT,
  "created_at" TEXT
);

CREATE TABLE "robo_raw"."patients" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "clinic_id" TEXT,
  "patient_code" TEXT,
  "full_name" TEXT,
  "date_of_birth" TEXT,
  "gender" TEXT,
  "id_number" TEXT,
  "id_type" TEXT,
  "phone_primary" TEXT,
  "phone_secondary" TEXT,
  "email" TEXT,
  "address" TEXT,
  "district" TEXT,
  "city" TEXT,
  "emergency_contact_name" TEXT,
  "emergency_contact_phone" TEXT,
  "emergency_contact_relationship" TEXT,
  "blood_type" TEXT,
  "allergies_notes" TEXT,
  "chronic_conditions_notes" TEXT,
  "insurance_number" TEXT,
  "insurance_provider" TEXT,
  "insurance_expiry" TEXT,
  "notes" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "created_by" TEXT,
  "updated_by" TEXT,
  "is_deleted" TEXT,
  "deleted_at" TEXT,
  "deleted_by" TEXT,
  "deletion_reason" TEXT,
  "patient_category" TEXT,
  "telegram_chat_id" TEXT,
  "telegram_username" TEXT
);

CREATE TABLE "robo_raw"."platform_admins" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "user_id" TEXT,
  "is_active" TEXT,
  "created_at" TEXT,
  "created_by" TEXT,
  "updated_at" TEXT,
  "deactivated_at" TEXT,
  "deactivated_reason" TEXT
);

CREATE TABLE "robo_raw"."platform_pricing_config" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "tier_name" TEXT,
  "min_appointments" TEXT,
  "max_appointments" TEXT,
  "unit_price_vnd" TEXT,
  "effective_from" TEXT,
  "effective_to" TEXT,
  "is_active" TEXT,
  "description" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

CREATE TABLE "robo_raw"."profiles" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "full_name" TEXT,
  "display_name" TEXT,
  "phone" TEXT,
  "avatar_url" TEXT,
  "license_number" TEXT,
  "specialty" TEXT,
  "title" TEXT,
  "signature_url" TEXT,
  "preferred_language" TEXT,
  "notification_settings" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "is_deleted" TEXT,
  "deleted_at" TEXT,
  "user_id" TEXT,
  "created_by" TEXT,
  "academic_title" TEXT,
  "sub_specialty" TEXT,
  "years_of_experience" TEXT,
  "position" TEXT,
  "workplaces" TEXT,
  "bio" TEXT,
  "license_document_url" TEXT,
  "email" TEXT
);

CREATE TABLE "robo_raw"."ref_clinic_type_features" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "clinic_type" TEXT,
  "feature_code" TEXT,
  "feature_name" TEXT,
  "feature_name_vi" TEXT,
  "description" TEXT,
  "is_default_enabled" TEXT,
  "display_order" TEXT
);

CREATE TABLE "robo_raw"."ref_currencies" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "code" TEXT,
  "name_vi" TEXT,
  "name_en" TEXT,
  "symbol" TEXT,
  "decimal_places" TEXT,
  "is_active" TEXT,
  "display_order" TEXT,
  "created_at" TEXT
);

CREATE TABLE "robo_raw"."ref_icd10_codes" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "code" TEXT,
  "name_vi" TEXT,
  "name_en" TEXT,
  "category" TEXT,
  "chapter" TEXT,
  "is_active" TEXT,
  "display_order" TEXT,
  "created_at" TEXT
);

CREATE TABLE "robo_raw"."rooms" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "clinic_id" TEXT,
  "room_code" TEXT,
  "room_name" TEXT,
  "room_type" TEXT,
  "floor" TEXT,
  "capacity" TEXT,
  "is_active" TEXT,
  "display_order" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "created_by" TEXT,
  "updated_by" TEXT
);

CREATE TABLE "robo_raw"."security_check_results" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "category" TEXT,
  "check_name" TEXT,
  "status" TEXT,
  "severity" TEXT,
  "details" TEXT,
  "detected_at" TEXT,
  "is_blocking" TEXT
);

CREATE TABLE "robo_raw"."sensitive_field_definitions" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "field_key" TEXT,
  "field_label" TEXT,
  "field_label_en" TEXT,
  "table_name" TEXT,
  "column_name" TEXT,
  "description" TEXT,
  "is_active" TEXT,
  "display_order" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "created_by" TEXT,
  "updated_by" TEXT
);

CREATE TABLE "robo_raw"."service_catalog" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "clinic_id" TEXT,
  "code" TEXT,
  "name" TEXT,
  "name_en" TEXT,
  "description" TEXT,
  "category_id" TEXT,
  "price_vnd" TEXT,
  "min_price_vnd" TEXT,
  "max_price_vnd" TEXT,
  "is_taxable" TEXT,
  "tax_rate_percent" TEXT,
  "duration_minutes" TEXT,
  "is_active" TEXT,
  "requires_doctor" TEXT,
  "display_order" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "created_by" TEXT,
  "updated_by" TEXT,
  "is_deleted" TEXT,
  "deleted_at" TEXT,
  "deleted_by" TEXT,
  "name_km" TEXT,
  "currency_code" TEXT,
  "result_turnaround_minutes" TEXT,
  "service_type" TEXT,
  "price_amount" TEXT,
  "price_effective_from" TEXT,
  "display_converted_amount" TEXT,
  "display_converted_currency_code" TEXT,
  "display_fx_computed_at" TEXT,
  "lab_subtype" TEXT
);

CREATE TABLE "robo_raw"."service_categories" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "clinic_id" TEXT,
  "name" TEXT,
  "name_en" TEXT,
  "description" TEXT,
  "display_order" TEXT,
  "is_active" TEXT,
  "parent_id" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "created_by" TEXT,
  "updated_by" TEXT,
  "is_deleted" TEXT,
  "deleted_at" TEXT,
  "deleted_by" TEXT,
  "name_km" TEXT
);

CREATE TABLE "robo_raw"."service_lab_indicators" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "service_id" TEXT,
  "clinic_id" TEXT,
  "code" TEXT,
  "name" TEXT,
  "name_en" TEXT,
  "name_km" TEXT,
  "unit" TEXT,
  "reference_range_text" TEXT,
  "reference_range_low" TEXT,
  "reference_range_high" TEXT,
  "specimen_type" TEXT,
  "method" TEXT,
  "display_order" TEXT,
  "is_active" TEXT,
  "is_deleted" TEXT,
  "deleted_at" TEXT,
  "deleted_by" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "created_by" TEXT,
  "updated_by" TEXT
);

CREATE TABLE "robo_raw"."service_package_items" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "clinic_id" TEXT,
  "package_id" TEXT,
  "service_id" TEXT,
  "quantity" TEXT,
  "notes" TEXT,
  "created_at" TEXT
);

CREATE TABLE "robo_raw"."service_packages" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "clinic_id" TEXT,
  "code" TEXT,
  "name" TEXT,
  "name_en" TEXT,
  "description" TEXT,
  "package_price_vnd" TEXT,
  "original_price_vnd" TEXT,
  "discount_percent" TEXT,
  "is_active" TEXT,
  "display_order" TEXT,
  "valid_days" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "created_by" TEXT,
  "updated_by" TEXT,
  "is_deleted" TEXT,
  "deleted_at" TEXT,
  "deleted_by" TEXT,
  "name_km" TEXT,
  "currency_code" TEXT
);

CREATE TABLE "robo_raw"."staff" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "clinic_id" TEXT,
  "full_name" TEXT,
  "phone" TEXT,
  "email" TEXT,
  "role" TEXT,
  "employee_code" TEXT,
  "date_of_birth" TEXT,
  "gender" TEXT,
  "address" TEXT,
  "id_card_number" TEXT,
  "start_date" TEXT,
  "end_date" TEXT,
  "is_active" TEXT,
  "academic_title" TEXT,
  "specialty" TEXT,
  "sub_specialty" TEXT,
  "years_of_experience" TEXT,
  "license_number" TEXT,
  "license_document_url" TEXT,
  "position" TEXT,
  "workplaces" TEXT,
  "bio" TEXT,
  "avatar_url" TEXT,
  "nursing_certificate" TEXT,
  "nursing_level" TEXT,
  "user_id" TEXT,
  "created_at" TEXT,
  "created_by" TEXT,
  "updated_at" TEXT,
  "updated_by" TEXT,
  "pharmacy_degree" TEXT,
  "pharmacy_certificate" TEXT,
  "pharmacy_license_number" TEXT,
  "pharmacy_specialization" TEXT
);

CREATE TABLE "robo_raw"."subscription_plans" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "plan_code" TEXT,
  "name" TEXT,
  "name_en" TEXT,
  "description" TEXT,
  "price_monthly_vnd" TEXT,
  "price_yearly_vnd" TEXT,
  "max_staff" TEXT,
  "max_patients" TEXT,
  "max_appointments_per_month" TEXT,
  "max_storage_gb" TEXT,
  "ai_level" TEXT,
  "ai_calls_per_month" TEXT,
  "features" TEXT,
  "display_order" TEXT,
  "is_active" TEXT,
  "is_public" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

CREATE TABLE "robo_raw"."tasks" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "clinic_id" TEXT,
  "board_id" TEXT,
  "parent_task_id" TEXT,
  "title" TEXT,
  "description" TEXT,
  "status" TEXT,
  "priority" TEXT,
  "assigned_to" TEXT,
  "created_by" TEXT,
  "due_date" TEXT,
  "due_time" TEXT,
  "started_at" TEXT,
  "completed_at" TEXT,
  "display_order" TEXT,
  "cover_color" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

CREATE TABLE "robo_raw"."translations" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "translation_key" TEXT,
  "language_code" TEXT,
  "value" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "created_by" TEXT,
  "updated_by" TEXT
);

CREATE TABLE "robo_raw"."user_roles" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "user_id" TEXT,
  "clinic_id" TEXT,
  "role" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "created_by" TEXT,
  "updated_by" TEXT,
  "is_deleted" TEXT,
  "deleted_at" TEXT,
  "deleted_by" TEXT
);

CREATE TABLE "robo_raw"."visits" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "clinic_id" TEXT,
  "patient_id" TEXT,
  "appointment_id" TEXT,
  "doctor_id" TEXT,
  "visit_number" TEXT,
  "visit_date" TEXT,
  "check_in_time" TEXT,
  "check_out_time" TEXT,
  "visit_type" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "created_by" TEXT,
  "updated_by" TEXT,
  "is_deleted" TEXT,
  "deleted_at" TEXT,
  "deleted_by" TEXT
);

CREATE TABLE "robo_raw"."vital_signs" (
  "_excel_row_number" INTEGER NOT NULL,
  "id" TEXT,
  "clinic_id" TEXT,
  "visit_id" TEXT,
  "patient_id" TEXT,
  "recorded_at" TEXT,
  "recorded_by" TEXT,
  "blood_pressure_systolic" TEXT,
  "blood_pressure_diastolic" TEXT,
  "heart_rate" TEXT,
  "respiratory_rate" TEXT,
  "temperature_celsius" TEXT,
  "oxygen_saturation" TEXT,
  "weight_kg" TEXT,
  "height_cm" TEXT,
  "bmi" TEXT,
  "notes" TEXT,
  "ai_anomaly_detected" TEXT,
  "ai_anomaly_notes" TEXT,
  "anomaly_reviewed_by" TEXT,
  "anomaly_reviewed_at" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "created_by" TEXT,
  "updated_by" TEXT,
  "is_deleted" TEXT,
  "deleted_at" TEXT,
  "deleted_by" TEXT
);
